version: '2'
services:

  ### Mysql container
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edfs
      MYSQL_USER: root2
      MYSQL_PASSWORD: root2
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: edfs_mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db